export const ERROR_CODES = {
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	UNAUTHORIZED: 'UNAUTHORIZED',
	VALIDATION_FAILED: 'VALIDATION_FAILED',
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
	USER_INVALID_CREDENTIALS: 'USER_INVALID_CREDENTIALS',
} as const

export type ErrorCode = keyof typeof ERROR_CODES
